### ISSUE TITLE
Data type unread count

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#1]
Data type of unread count should always be INTEGER.

API - http://herelo.com/Herelo_ms3/public/index.php/api/getGroupChatList?user_id=2

Please send unread_msg param in integer form.

**Comment by backend-techvalens** [comment]
Changed it to the int. Please verify and close the issue. Also changed the param name to unread_count.

**Comment by devtechvalens** [comment]
param name is changed and Also getting int type.
Thanks
