### ISSUE TITLE
Offline Notification API required

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#4]
To send offline XMPP users for notifications.

**Comment by backend-techvalens** [comment]
**Here are the details for the API:**
**params:** offline_users [{"user_id":<value>,"username":<value>}], group_id, user_id, message
**Method:** Post
**End Point:** addGroupChatNotify


**In activity log:**
notification_type: NEWMESSAGE

**Comment by backend-techvalens** [comment]
**Example ran on postman:**
**URL:** http://herelo.com/Herelo_ms3/public/index.php/api/addGroupChatNotify
**Header:** "Content-Type":"application/json"
**Param:**
{
"user_id":"2",
"group_id":"193",
"message":{
  "img" : "",
  "dt" : "1528902300524",
  "v_thumb" : "",
  "vid" : "",
  "text" : "dfghfgh",
  "user_id" : "2",
  "type" : "txt",
  "sender_image" : "image3E9D1DBD-3F2D-4ECE-B549-EF18F32BB4CC.png"
},
"offline_users":[{"user_id":54,"username":"ankush"}]
}
