### ISSUE TITLE
Update response for API: addGroup

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#6]
Please update response of API as, newly created group info should be be out of all groups array.

**Comment by backend-techvalens** [comment]
Requested for the group_id previously, do I need to add the entire group object in that one?

**Comment by devtechvalens** [comment]
Yes please provide the whole recently group object into JSON object.

**Comment by backend-techvalens** [comment]
Made it.

**Comment by backend-techvalens** [comment]
Param name is new_group
