### ISSUE TITLE
Request to be update in API: addUserGroup 

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#7]
Request should be in Json for groupids. Now its asking for comma separated string.

**Comment by backend-techvalens** [comment]
It is already implemented in iOS, do you guys still need to update the API?
If I am going to change this one. It will need to be updated on both end

**Comment by devtechvalens** [comment]
From now NO COMMA SEPARATED, it must me JSON ARRAY
All side changes required

**Comment by backend-techvalens** [comment]
Made It
