### ISSUE TITLE
Message type  "NOTIFICATION" in chat History API

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#8]
DO NOT provide new **message_type**, it should always be "**NOTIFICATION**" that must contains "**message**" in "txt" field inside "body"

1. Change the message_type to NOTIFICATION
2. When user(s) added/removed into group.
3. When group name updated.

**Comment by backend-techvalens** [comment]
{
   "status": 1,
   "data": [
       {
           "body": "{\"type\":\"NOTIFICATION\",\"user_id\":\"2\",\"user_name\":\"Shoeb\",\"activity\":\"New Member\",\"txt\":\"You added Shoeb to this group\"}",
           "fromJID": "ankush",
           "is_mine": 1,
           "sentDate": 1529566024,
           "toJID": "tset",
           "id": 2209,
           "user_images": "imageCAF409EB-F63F-4F2A-947C-6ECEA2C1E089.png"
       }
   ]
}
This kind of responce will be in the history api.

**Comment by devtechvalens** [comment]
Please provide this response.

**Comment by devtechvalens** [comment]
{
"body": "{"type":"NOTIFICATION","user_id":"2","user_name":"Shoeb","activity":"New Member","**text**":"You added Shoeb to this group"}

body should give **text**
