### ISSUE TITLE
Group not be created.

### ISSUE THREAD

**Issue by devtechvalens** [devtechvalens/HereLo-API#9]
![screenshot from 2018-06-21 15-00-50](https://user-images.githubusercontent.com/25582828/41711032-bb42ec06-7564-11e8-9731-08a04afdcc58.png)

{"group_name":"spider","user_id":54,"users":[{"role":[1],"user_id":2,"username":"Shoeb"},{"role":[1],"user_id":19,"username":"Aakash"}]}

http://herelo.com/Herelo_ms3/public/index.php/api/addGroup

Please check

**Comment by backend-techvalens** [comment]
Fixed it. Please Check.
